#######################################
######     Pkgs & Data     ############
#######################################

#install.packages("plm")
library(plm)
#install.packages("zoo")
library(zoo)
#install.packages("readr")
library(readr)
#install.packages("dplyr")
library(dplyr)
#install.packages("plotrix")
library(plotrix)
#install.packages("rJava")
library(rJava)
#install.packages("knitr")
library(knitr)
#install.packages("rmarkdown")
library(rmarkdown)
#install.packages("plotly")
library(plotly)


#install.packages("colorspace")
library(colorspace)
#install.packages("ggplot2")
library(ggplot2)
#install.packages("data.table")
library(data.table)
#install.packages("xlsx")
#library(xlsx)
#install.packages("XML")
#library(XML)
#install.packages("tydyr")
#library(tidyr)
#install.packages("swirl")
#library(swirl)
#install_from_swirl("Getting and Cleaning Data")


#install.packages("httpuv")
#library(httpuv)
#install.packages("jsonlite")
#library(jsonlite)
#install.packages("httr")
#library(httr)
#install.packages("RCurl")
#library(RCurl)


#library(survey)
# install.packages("foreign")
#library(foreign)
# install.packages("gmodels")
#library(gmodels)
# install.packages("weights")
#library(weights)
# install.packages("reshape")
#library(reshape)
# install.packages("corrgram")
#library(corrgram)
# install.packages("Hmisc")
#library(Hmisc)
#install.packages("lme4")
#library(lme4)
#install.packages("survey")
#library(survey)
#install.packages("stargazer")
#library(stargazer)
#install.packages("pROC")
#library(pROC)
